apiVersion: v1
kind: Pod
metadata:
  name: result-front-end-app
  labels:
    tier: frontend-result
    app: demo-voting-app
spec:
  containers:
    - name: result-vote-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80