apiVersion: v1
kind: Pod
metadata:
  name: vote-front-end-app
  labels:
    tier: frontend-vote
    app: demo-voting-app
spec:
  containers:
    - name: front-end-vote-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80