apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    name: workerapp
    tier: backend
    app: demo-voting-app

spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
